name = "lean4checker"
defaultTargets = ["Lean4Checker", "lean4checker", "Lean4CheckerTests"]
testDriver = "lean4checker_test"

[[lean_lib]]
name = "Lean4Checker"
globs = ["Lean4Checker.*"]

[[lean_lib]]
name = "Lean4CheckerTests"
globs = ["Lean4CheckerTests.*"]

[[lean_exe]]
name = "lean4checker"
root = "Main"
supportInterpreter = true
dependencies = ["Lean_RV64D"]

[[lean_exe]]
name = "lean4checker_test"
root = "Lean4CheckerTests.TestDriver"

[[require]]
name = "Lean_RV64D"
git = "https://github.com/opencompl/sail-riscv-lean"
rev = "lean-2025-08-02"

[[require]]
name = "SSA"
git = "https://github.com/opencompl/lean-mlir"
rev = "auto-mathlib-update-2025-08-02"
